### ISSUE TITLE
Having too many notes & scrolling causes crash

### ISSUE THREAD

**Issue by zanedb** [openssf/open-journal-android#24]
Will look into this soon, big bug.

**Comment by zanedb** [comment]
Just did some testing, got this log output:

	10-14 09:08:17.930 2573-2599/org.openssf.openjournal E/OpenGLRenderer: Corrupted GPU pixel buffer
	10-14 09:08:18.114 2573-2599/org.openssf.openjournal D/EGL_emulation: eglMakeCurrent: 0x9b66ee80: ver 3 1 (tinfo 0x9d6eac00)
	10-14 09:08:18.187 2573-2573/org.openssf.openjournal W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
	10-14 09:08:23.361 2573-2573/org.openssf.openjournal E/CursorWindow: Could not allocate CursorWindow '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' of size 2097152 due to error -12.
	10-14 09:08:23.362 2573-2573/org.openssf.openjournal D/AndroidRuntime: Shutting down VM
                                                                       
                                                                       
                                                                       --------- beginning of crash
	10-14 09:08:23.363 2573-2573/org.openssf.openjournal E/AndroidRuntime: FATAL EXCEPTION: main
	                                                                       Process: org.openssf.openjournal, PID: 2573
	                                                                       android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=822 (# cursors opened by this proc=822)
        	                                                                   at android.database.CursorWindow.<init>(CursorWindow.java:108)
                	                                                           at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
                        	                                                   at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
                                	                                           at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	                                                                           at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	                                                                           at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
        	                                                                   at org.openssf.openjournal.utils.DBHelper.getNoteIdFromTitle(DBHelper.java:111)
                	                                                           at org.openssf.openjournal.NotesAdapter.onBindViewHolder(NotesAdapter.java:69)
                        	                                                   at org.openssf.openjournal.NotesAdapter.onBindViewHolder(NotesAdapter.java:23)
                                	                                           at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                        	                                   at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                	                           at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                        	                   at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                	           at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                                                                        	   at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
	                                                                           at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
        	                                                                   at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                	                                                           at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                        	                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                	                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                        	                                   at android.os.Looper.loop(Looper.java:154)
                                                	                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                        	                   at java.lang.reflect.Method.invoke(Native Method)
                                                                	           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                        	   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
	10-14 09:08:29.752 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.754 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.754 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.755 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.755 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.756 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.756 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.756 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.757 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.759 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.760 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.761 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.762 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.762 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
	10-14 09:08:29.763 2573-2583/org.openssf.openjournal W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.openssf.openjournal/databases/openJournalDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

Indicating that it is a SQL error<sup>by my bad code</sup>. I will fix this soon.

**Comment by zanedb** [comment]
Fixed [here](https://github.com/openssf/open-journal-android/commit/2f06052e054611f827be6698d1b5a66055cbeb48), but just noticed another issue in the log above, #27
